<?=$add_cookie?><br>
<?=$read_cookie?><br>
<?=$remove_cookie?><br>
<hr>
<?=$add_session?><br>
<?=$read_session?><br>
<?=$remove_session?><br>
<hr>
<?=$add_my_sql?><br>
<?=$read_my_sql?><br>
<?=$remove_my_sql?><br>
